version: "3"
services:
  zookeeper:
    image: zookeeper:latest
    container_name: my_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: my_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  server:
    build: ./server
    depends_on:
      - kafka
    ports:
      - "5000:5000"
    env_file:
      - .env
      - ./server/.env
    environment:
      - PORT=${SERVER_PORT}
      - KAFKA_BROKER=${KAFKA_BROKER}
    command: ["./wait-for-it.sh", "kafka", "9092", "--", "npm", "start"]
    restart: always

  payment-service:
    build: ./payment-service
    depends_on:
      - kafka
    ports:
      - "5001:5001"
    env_file:
      - .env
      - ./payment-service/.env
    environment:
      - PORT=${PAYMENT_SERVICE_PORT}
      - KAFKA_BROKER=${KAFKA_BROKER}
    command: ["./wait-for-it.sh", "kafka", "9092", "--", "npm", "start"]
    restart: always

  notification-service:
    build: ./notification-service
    depends_on:
      - kafka
    ports:
      - "5002:5002"
    env_file:
      - .env
      - ./notification-service/.env
    environment:
      - PORT=${NOTIFICATION_SERVICE_PORT}
      - KAFKA_BROKER=${KAFKA_BROKER}
    command: ["./wait-for-it.sh", "kafka", "9092", "--", "npm", "start"]
    restart: always
